version: '2'

services:
    web1:
        container_name: "sugar-web1"
        image: sugar77_php56_web
        build: ../../images/php/56/apache
        ports:
            - "80:80"
        extra_hosts:
            - "docker.local:127.0.0.1"
        volumes:
            - ../../data/app:/var/www/html
        depends_on:
            - mysql
            - elasticsearch
            - redis
            - permissions
        links:
            - mysql
            - elasticsearch
            - redis
    cron:
        container_name: "sugar-cron"
        image: sugar77_php56_cron
        build: ../../images/php/56/cron
        volumes:
            - ../../data/app:/var/www/html
        depends_on:
            - mysql
            - elasticsearch
            - redis
            - permissions
        links:
            - mysql
            - elasticsearch
            - redis
    mysql:
        container_name: "sugar-mysql"
        image: sugar77_mysql
        build: ../../images/mysql/56
        ports:
            - "3306:3306"
        volumes:
            - ../../data/mysql/56:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=sugar
            - MYSQL_PASSWORD=sugar
    elasticsearch:
        container_name: "sugar-elasticsearch"
        image: sugar77_elastic144
        build: ../../images/elasticsearch/144
        volumes:
            - ../../data/elasticsearch/144:/usr/share/elasticsearch/data
    redis:
        container_name: "sugar-redis"
        image: redis:latest
        volumes:
            - ../../data/redis:/data
    permissions:
        container_name: "sugar-permissions"
        image: sugar77_permissions
        build: ../../images/permissions
        volumes:
            - ../../data/app:/var/www/html
