version: '2'

services:
    web1:
        container_name: "sugar-web1"
        image: esimonetti/sugardockerized:php5.6-apache-1.14
        ports:
            - "80:80"
        extra_hosts:
            - "docker.local:127.0.0.1"
        volumes:
            - ../../data/app:/var/www/html
        depends_on:
            - mysql
            - elasticsearch
            - redis
            - permissions
            - ldap
        links:
            - mysql
            - elasticsearch
            - redis
            - ldap
    cron:
        container_name: "sugar-cron"
        image: esimonetti/sugardockerized:php5.6-cron
        volumes:
            - ../../data/app:/var/www/html
        depends_on:
            - mysql
            - elasticsearch
            - redis
            - permissions
            - ldap
        links:
            - mysql
            - elasticsearch
            - redis
            - ldap
    mysql:
        container_name: "sugar-mysql"
        image: esimonetti/sugardockerized:mysql5.7-1.06
        ports:
            - "3306:3306"
        volumes:
            - ../../data/mysql/57:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=sugar
            - MYSQL_PASSWORD=sugar
    elasticsearch:
        container_name: "sugar-elasticsearch"
        image: esimonetti/sugardockerized:elasticsearch1.7.5
        volumes:
            - ../../data/elasticsearch/175:/usr/share/elasticsearch/data
    redis:
        container_name: "sugar-redis"
        image: redis:latest
        volumes:
            - ../../data/redis:/data
    permissions:
        container_name: "sugar-permissions"
        image: esimonetti/sugardockerized:permissions-1.19
        volumes:
            - ../../data/app:/var/www/html
    ldap:
        container_name: "sugar-ldap"
        image: esimonetti/sugardockerized:ldap
        ports:
            - "389:389"
        volumes:
            - ../../data/ldap/var:/var/lib/ldap
            - ../../data/ldap/etc:/etc/ldap
