version: '2'

services:
    lb:
        container_name: "sugar-lb"
        image: esimonetti/sugardockerized:loadbalancer
        ports:
            - "80:80"
        depends_on:
            - web1
            - web2
        links:
            - web1
            - web2
    web1:
        container_name: "sugar-web1"
        image: esimonetti/sugardockerized:php7.1-apache-1.28
        extra_hosts:
            - "docker.local:127.0.0.1"
        environment:
            - "APACHE_RUN_USER=sugar"
            - "APACHE_RUN_GROUP=sugar"
        volumes:
            - ../../data/app:/var/www/html
        depends_on:
            - mysql
            - elasticsearch
            - redis
            - permissions
            - mailhog
        links:
            - mysql
            - elasticsearch
            - redis
            - mailhog
    web2:
        container_name: "sugar-web2"
        image: esimonetti/sugardockerized:php7.1-apache-1.28
        extra_hosts:
            - "docker.local:127.0.0.1"
        environment:
            - "APACHE_RUN_USER=sugar"
            - "APACHE_RUN_GROUP=sugar"
        volumes:
            - ../../data/app:/var/www/html
        depends_on:
            - mysql
            - elasticsearch
            - redis
            - permissions
            - mailhog
        links:
            - mysql
            - elasticsearch
            - redis
            - mailhog
    cron:
        container_name: "sugar-cron"
        image: esimonetti/sugardockerized:php7.1-cron-1.28
        volumes:
            - ../../data/app:/var/www/html
        depends_on:
            - mysql
            - elasticsearch
            - redis
            - permissions
            - mailhog
        links:
            - mysql
            - elasticsearch
            - redis
            - mailhog
    mysql:
        container_name: "sugar-mysql"
        image: esimonetti/sugardockerized:mysql5.7-1.06
        ports:
            - "3306:3306"
        volumes:
            - ../../data/mysql/57:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=sugar
            - MYSQL_PASSWORD=sugar
    elasticsearch:
        container_name: "sugar-elasticsearch"
        image: esimonetti/sugardockerized:elasticsearch1.7.5
        volumes:
            - ../../data/elasticsearch/175:/usr/share/elasticsearch/data
    redis:
        container_name: "sugar-redis"
        image: redis:latest
        volumes:
            - ../../data/redis:/data
    permissions:
        container_name: "sugar-permissions"
        image: esimonetti/sugardockerized:permissions-1.19
        volumes:
            - ../../data/app:/var/www/html
    mailhog:
        container_name: "sugar-mailhog"
        image: mailhog/mailhog:latest
        ports:
            - "8025:8025"
