version: '3'

services:
    web1:
        container_name: "sugar-web1"
        image: sugar_php74_web
        ports:
            - "8080:80"
        extra_hosts:                                   
            - "docker.local:127.0.0.1"                        
        environment:
            - "APACHE_RUN_USER=sugar"
            - "APACHE_RUN_GROUP=sugar"
        volumes:
            - ../../data/app:/var/www/html
        depends_on:
            - mysql
            - elasticsearch
            - redis
            - permissions
        links:
            - mysql
            - elasticsearch
            - redis
    cron:
        container_name: "sugar-cron"
        image: sugar_php74_cron        
        volumes:
            - ../../data/app:/var/www/html
        depends_on:
            - mysql
            - elasticsearch
            - redis
            - permissions
        links:            
            - mysql
            - elasticsearch
            - redis  
    mysql:
        container_name: "sugar-mysql"
        image: sugar_mysql
        ports:
            - "3306:3306"
        volumes:
            - ../../data/mysql/57:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=sugar
            - MYSQL_PASSWORD=sugar
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
        container_name: "sugar-elasticsearch"
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - es-data01:/usr/share/elasticsearch/data
        environment:
            - node.name=sugar1
            - cluster.name=sugarcrm79
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
    redis:
        container_name: "sugar-redis"
        image: redis:latest
        volumes:
            - ../../data/redis:/data
    permissions:
        container_name: "sugar-permissions"
        image: sugar_permissions
        volumes:
            - ../../data/app:/var/www/html