#!/usr/bin/env bash

#echo fs.inotify.max_user_watches=1000000 | tee -a /etc/sysctl.conf && sysctl -p

rsync -av --delete /hostfs/* /volumefs >> /var/logs/filesync.log
unison app >> /var/logs/filesync.log
