version: '3'

# in this mac attempt, redis, elasticsearch and mysql files are stored within a volume (not on a bin mounted directory) and everything is delegated (priority to the containers)

services:
    web1:
        container_name: "sugar-web1"
        image: esimonetti/sugardockerized:php7.3-apache-1.40
        ports:
            - "80:80"
        extra_hosts:
            - "docker.local:127.0.0.1"
        environment:
            - "APACHE_RUN_USER=sugar"
            - "APACHE_RUN_GROUP=sugar"
        volumes:
            - ../../data/app:/var/www/html:delegated
        depends_on:
            - mysql
            - elasticsearch
            - redis
            - permissions
            - mailhog
        links:
            - mysql
            - elasticsearch
            - redis
            - mailhog
    cron:
        container_name: "sugar-cron"
        image: esimonetti/sugardockerized:php7.3-cron-1.40
        volumes:
            - ../../data/app:/var/www/html:delegated
        depends_on:
            - mysql
            - elasticsearch
            - redis
            - permissions
            - mailhog
        links:
            - mysql
            - elasticsearch
            - redis
            - mailhog
    mysql:
        container_name: "sugar-mysql"
        image: esimonetti/sugardockerized:mysql5.7-1.06
        ports:
            - "3306:3306"
        volumes:
            - sugar-mysql-data:/var/lib/mysql:delegated
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=sugar
            - MYSQL_PASSWORD=sugar
    elasticsearch:
        container_name: "sugar-elasticsearch"
        image: esimonetti/sugardockerized:elasticsearch6.2-1.07
        volumes:
            - sugar-elasticsearch-data:/usr/share/elasticsearch/data:delegated
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "TAKE_FILE_OWNERSHIP=true"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
    redis:
        container_name: "sugar-redis"
        image: redis:latest
        volumes:
            - sugar-redis-data:/data:delegated
    permissions:
        container_name: "sugar-permissions"
        image: esimonetti/sugardockerized:permissions-1.19
        volumes:
            - ../../data/app:/var/www/html:delegated
    mailhog:
        container_name: "sugar-mailhog"
        image: mailhog/mailhog:latest
        ports:
            - "8025:8025"
volumes:
    sugar-mysql-data:
    sugar-redis-data:
    sugar-elasticsearch-data:
