FROM docker.elastic.co/elasticsearch/elasticsearch:7.9.0


# RUN bin/elasticsearch-plugin remove x-pack

COPY config/elasticsearch/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml